pkg/ipc: remove use of reflect.SliceHeader
Linter now complains:

Error: SA1019: reflect.SliceHeader has been deprecated since Go 1.21
and an alternative has been available since Go 1.17:
Use unsafe.Slice or unsafe.SliceData instead.