executor: include missing header
FreeBSD says:

executor/conn.h:100:3: error: unknown type name 'sockaddr_in'; did you mean 'sockaddr'?
           sockaddr_in saddr4 = {};