tools/docker/syzbot: add libbpf-dev to Dockerfile
gVisor relies on eBPF since the following 2 commits, so libbpf-dev is
required when building:

- https://github.com/google/gvisor/commit/2ae19ffb
- https://github.com/google/gvisor/commit/f6d380ad

Without this change, syzkaller can't build gVisor and gets the following
error:

  tools/xdp/cmd/bpf/redirect_host.ebpf.c:15:10: fatal error: 'bpf/bpf_endian.h' file not found
  FAILED: Build did NOT complete successfully